"""initial_schema

Revision ID: 1001
Revises: 
Create Date: 2026-06-27 20:57:47.374609

"""
from typing import Sequence, Union

from sqlmodel import AutoString
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_definitions',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('key', AutoString(length=50), nullable=False),
    sa.Column('display_name', AutoString(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', AutoString(length=20), nullable=False),
    sa.Column('prompt_agent_name', AutoString(length=50), nullable=False),
    sa.Column('model_id', AutoString(length=100), nullable=True),
    sa.Column('tool_category_keys_json', sa.JSON(), nullable=False),
    sa.Column('enabled_skill_ids_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('source', AutoString(length=20), nullable=False),
    sa.Column('delegatable_agents', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_definitions_enabled'), 'agent_definitions', ['enabled'], unique=False)
    op.create_index(op.f('ix_agent_definitions_key'), 'agent_definitions', ['key'], unique=True)
    op.create_index(op.f('ix_agent_definitions_kind'), 'agent_definitions', ['kind'], unique=False)
    op.create_index(op.f('ix_agent_definitions_order_index'), 'agent_definitions', ['order_index'], unique=False)
    op.create_index(op.f('ix_agent_definitions_source'), 'agent_definitions', ['source'], unique=False)
    op.create_table('agent_memories',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('content', AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_rules',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('title', AutoString(), nullable=False),
    sa.Column('content', AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('background_jobs',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('type', AutoString(length=80), nullable=False),
    sa.Column('status', AutoString(length=30), nullable=False),
    sa.Column('queue', AutoString(length=80), nullable=False),
    sa.Column('subject_type', AutoString(length=80), nullable=True),
    sa.Column('subject_id', AutoString(), nullable=True),
    sa.Column('payload_json', AutoString(), nullable=False),
    sa.Column('context_json', AutoString(), nullable=False),
    sa.Column('progress_json', AutoString(), nullable=False),
    sa.Column('result_json', AutoString(), nullable=True),
    sa.Column('error_json', AutoString(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('event_sequence', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by', AutoString(length=100), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_reason', AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_jobs_cancel_requested_at'), 'background_jobs', ['cancel_requested_at'], unique=False)
    op.create_index(op.f('ix_background_jobs_heartbeat_at'), 'background_jobs', ['heartbeat_at'], unique=False)
    op.create_index(op.f('ix_background_jobs_lease_expires_at'), 'background_jobs', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_background_jobs_locked_at'), 'background_jobs', ['locked_at'], unique=False)
    op.create_index(op.f('ix_background_jobs_locked_by'), 'background_jobs', ['locked_by'], unique=False)
    op.create_index(op.f('ix_background_jobs_next_run_at'), 'background_jobs', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_background_jobs_queue'), 'background_jobs', ['queue'], unique=False)
    op.create_index(op.f('ix_background_jobs_status'), 'background_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_background_jobs_subject_id'), 'background_jobs', ['subject_id'], unique=False)
    op.create_index(op.f('ix_background_jobs_subject_type'), 'background_jobs', ['subject_type'], unique=False)
    op.create_index(op.f('ix_background_jobs_type'), 'background_jobs', ['type'], unique=False)
    op.create_index(op.f('ix_background_jobs_updated_at'), 'background_jobs', ['updated_at'], unique=False)
    op.create_table('model_providers',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('name', AutoString(length=200), nullable=False),
    sa.Column('url', AutoString(length=500), nullable=False),
    sa.Column('api_key_encrypted', AutoString(length=1000), nullable=False),
    sa.Column('provider_type', AutoString(length=50), nullable=False),
    sa.Column('icon_path', AutoString(length=500), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('scope_id', AutoString(length=64), nullable=False),
    sa.Column('topic', AutoString(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', AutoString(length=20), nullable=False),
    sa.Column('parent_dependency_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_dependency_id'], ['plan_todos.id'], name='fk_plans_parent_dependency_id_plan_todos', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_dependency_id')
    )
    op.create_index(op.f('ix_plans_created_at'), 'plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_plans_scope_id'), 'plans', ['scope_id'], unique=False)
    op.create_index(op.f('ix_plans_status'), 'plans', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('title', AutoString(length=200), nullable=False),
    sa.Column('description', AutoString(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('chapter_count', sa.Integer(), nullable=False),
    sa.Column('cover_path', AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_chain_versions',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('mode_name', AutoString(length=100), nullable=False),
    sa.Column('task_name', AutoString(length=100), nullable=False),
    sa.Column('agent_name', AutoString(length=100), nullable=True),
    sa.Column('version_hash', AutoString(length=8), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_version_id'], ['prompt_chain_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_hash')
    )
    op.create_table('settings',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('key', AutoString(length=100), nullable=False),
    sa.Column('value', AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('skills',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('name', AutoString(length=200), nullable=False),
    sa.Column('summary', AutoString(), nullable=False),
    sa.Column('skill_id', AutoString(length=100), nullable=False),
    sa.Column('content', AutoString(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_is_enabled'), 'skills', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_skills_skill_id'), 'skills', ['skill_id'], unique=False)
    op.create_table('writing_activity_events',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', AutoString(), nullable=False),
    sa.Column('chapter_id', AutoString(), nullable=True),
    sa.Column('chapter_title', AutoString(length=200), nullable=True),
    sa.Column('source', AutoString(length=30), nullable=False),
    sa.Column('operation', AutoString(length=30), nullable=False),
    sa.Column('old_word_count', sa.Integer(), nullable=False),
    sa.Column('new_word_count', sa.Integer(), nullable=False),
    sa.Column('word_delta', sa.Integer(), nullable=False),
    sa.Column('revision_id', AutoString(), nullable=True),
    sa.Column('task_id', AutoString(), nullable=True),
    sa.Column('agent_session_id', AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writing_activity_events_agent_session_id'), 'writing_activity_events', ['agent_session_id'], unique=False)
    op.create_index(op.f('ix_writing_activity_events_chapter_id'), 'writing_activity_events', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_writing_activity_events_created_at'), 'writing_activity_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_writing_activity_events_operation'), 'writing_activity_events', ['operation'], unique=False)
    op.create_index(op.f('ix_writing_activity_events_project_id'), 'writing_activity_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_writing_activity_events_revision_id'), 'writing_activity_events', ['revision_id'], unique=False)
    op.create_index(op.f('ix_writing_activity_events_source'), 'writing_activity_events', ['source'], unique=False)
    op.create_index(op.f('ix_writing_activity_events_task_id'), 'writing_activity_events', ['task_id'], unique=False)
    op.create_table('background_job_items',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('job_id', AutoString(), nullable=False),
    sa.Column('item_key', AutoString(length=200), nullable=False),
    sa.Column('type', AutoString(length=80), nullable=False),
    sa.Column('status', AutoString(length=30), nullable=False),
    sa.Column('payload_json', AutoString(), nullable=False),
    sa.Column('result_json', AutoString(), nullable=True),
    sa.Column('error_json', AutoString(), nullable=True),
    sa.Column('progress_json', AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['background_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_job_items_item_key'), 'background_job_items', ['item_key'], unique=False)
    op.create_index(op.f('ix_background_job_items_job_id'), 'background_job_items', ['job_id'], unique=False)
    op.create_index(op.f('ix_background_job_items_order_index'), 'background_job_items', ['order_index'], unique=False)
    op.create_index(op.f('ix_background_job_items_status'), 'background_job_items', ['status'], unique=False)
    op.create_index(op.f('ix_background_job_items_type'), 'background_job_items', ['type'], unique=False)
    op.create_index(op.f('ix_background_job_items_updated_at'), 'background_job_items', ['updated_at'], unique=False)
    op.create_table('models',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('name', AutoString(length=200), nullable=False),
    sa.Column('remark', AutoString(length=500), nullable=False),
    sa.Column('provider_id', AutoString(), nullable=False),
    sa.Column('model_id', AutoString(length=200), nullable=False),
    sa.Column('task_type', AutoString(length=20), nullable=False),
    sa.Column('tags', AutoString(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('min_p', sa.Float(), nullable=True),
    sa.Column('top_a', sa.Float(), nullable=True),
    sa.Column('frequency_penalty', sa.Float(), nullable=True),
    sa.Column('presence_penalty', sa.Float(), nullable=True),
    sa.Column('repetition_penalty', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('context_length', sa.Integer(), nullable=False),
    sa.Column('deepseek_reasoning_effort', AutoString(length=20), nullable=True),
    sa.Column('deepseek_thinking_type', AutoString(length=20), nullable=True),
    sa.Column('dimensions', sa.Integer(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['model_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_provider_id'), 'models', ['provider_id'], unique=False)
    op.create_index(op.f('ix_models_task_type'), 'models', ['task_type'], unique=False)
    op.create_table('note_categories',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('project_id', AutoString(), nullable=False),
    sa.Column('parent_id', AutoString(), nullable=True),
    sa.Column('title', AutoString(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['note_categories.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_categories_parent_id'), 'note_categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_note_categories_project_id'), 'note_categories', ['project_id'], unique=False)
    op.create_table('plan_todos',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('plan_id', AutoString(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', AutoString(length=20), nullable=False),
    sa.Column('sort_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'sort_index', name='uq_plan_todos_plan_id_sort_index')
    )
    op.create_index(op.f('ix_plan_todos_created_at'), 'plan_todos', ['created_at'], unique=False)
    op.create_index(op.f('ix_plan_todos_plan_id'), 'plan_todos', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plan_todos_sort_index'), 'plan_todos', ['sort_index'], unique=False)
    op.create_index(op.f('ix_plan_todos_status'), 'plan_todos', ['status'], unique=False)
    op.create_table('prompt_entries',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('uid', AutoString(), nullable=False),
    sa.Column('version_id', AutoString(), nullable=False),
    sa.Column('name', AutoString(length=200), nullable=False),
    sa.Column('role', AutoString(length=20), nullable=False),
    sa.Column('content', AutoString(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['prompt_chain_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_entries_uid'), 'prompt_entries', ['uid'], unique=False)
    op.create_table('revisions',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('project_id', AutoString(), nullable=False),
    sa.Column('message', AutoString(), nullable=False),
    sa.Column('agent_session_id', AutoString(), nullable=True),
    sa.Column('status', AutoString(), nullable=False),
    sa.Column('revision_type', AutoString(), nullable=False),
    sa.Column('parent_revision_id', AutoString(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('user_message_id', AutoString(), nullable=True),
    sa.Column('user_message_seq', sa.Integer(), nullable=True),
    sa.Column('pre_run_checkpoint_id', AutoString(), nullable=True),
    sa.Column('graph_thread_id', AutoString(), nullable=True),
    sa.Column('is_checkpoint', sa.Boolean(), nullable=False),
    sa.Column('project_snapshot_title', AutoString(length=200), nullable=False),
    sa.Column('project_snapshot_description', AutoString(), nullable=True),
    sa.Column('project_snapshot_word_count', sa.Integer(), nullable=False),
    sa.Column('project_snapshot_chapter_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_revision_id'], ['revisions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='fk_revisions_task_id_tasks', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revisions_created_at'), 'revisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_revisions_finished_at'), 'revisions', ['finished_at'], unique=False)
    op.create_index(op.f('ix_revisions_graph_thread_id'), 'revisions', ['graph_thread_id'], unique=False)
    op.create_index(op.f('ix_revisions_is_checkpoint'), 'revisions', ['is_checkpoint'], unique=False)
    op.create_index(op.f('ix_revisions_parent_revision_id'), 'revisions', ['parent_revision_id'], unique=False)
    op.create_index(op.f('ix_revisions_pre_run_checkpoint_id'), 'revisions', ['pre_run_checkpoint_id'], unique=False)
    op.create_index(op.f('ix_revisions_project_id'), 'revisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_revisions_revision_type'), 'revisions', ['revision_type'], unique=False)
    op.create_index(op.f('ix_revisions_started_at'), 'revisions', ['started_at'], unique=False)
    op.create_index(op.f('ix_revisions_status'), 'revisions', ['status'], unique=False)
    op.create_index(op.f('ix_revisions_task_id'), 'revisions', ['task_id'], unique=False)
    op.create_index(op.f('ix_revisions_user_message_id'), 'revisions', ['user_message_id'], unique=False)
    op.create_index(op.f('ix_revisions_user_message_seq'), 'revisions', ['user_message_seq'], unique=False)
    op.create_table('volumes',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('project_id', AutoString(), nullable=False),
    sa.Column('title', AutoString(length=200), nullable=False),
    sa.Column('description', AutoString(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('chapter_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'order', name='uq_volumes_project_order')
    )
    op.create_index(op.f('ix_volumes_order'), 'volumes', ['order'], unique=False)
    op.create_index(op.f('ix_volumes_project_id'), 'volumes', ['project_id'], unique=False)
    op.create_table('world_info',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('project_id', AutoString(), nullable=True),
    sa.Column('name', AutoString(length=200), nullable=False),
    sa.Column('description', AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_info_project_id'), 'world_info', ['project_id'], unique=True)
    op.create_table('background_job_events',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('job_id', AutoString(), nullable=False),
    sa.Column('item_id', AutoString(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', AutoString(length=100), nullable=False),
    sa.Column('payload_json', AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['background_job_items.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['background_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_job_events_created_at'), 'background_job_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_background_job_events_event_type'), 'background_job_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_background_job_events_item_id'), 'background_job_events', ['item_id'], unique=False)
    op.create_index(op.f('ix_background_job_events_job_id'), 'background_job_events', ['job_id'], unique=False)
    op.create_index(op.f('ix_background_job_events_sequence'), 'background_job_events', ['sequence'], unique=False)
    op.create_table('chapters',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('project_id', AutoString(), nullable=False),
    sa.Column('volume_id', AutoString(), nullable=False),
    sa.Column('title', AutoString(length=200), nullable=False),
    sa.Column('content', AutoString(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['volume_id'], ['volumes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('volume_id', 'order', name='uq_chapters_volume_order')
    )
    op.create_index(op.f('ix_chapters_order'), 'chapters', ['order'], unique=False)
    op.create_index(op.f('ix_chapters_project_id'), 'chapters', ['project_id'], unique=False)
    op.create_index(op.f('ix_chapters_volume_id'), 'chapters', ['volume_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('project_id', AutoString(), nullable=False),
    sa.Column('category_id', AutoString(), nullable=True),
    sa.Column('title', AutoString(length=200), nullable=False),
    sa.Column('content', AutoString(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['note_categories.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_category_id'), 'notes', ['category_id'], unique=False)
    op.create_index(op.f('ix_notes_project_id'), 'notes', ['project_id'], unique=False)
    op.create_table('retrieval_indexes',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('index_key', AutoString(length=200), nullable=False),
    sa.Column('table_name', AutoString(length=200), nullable=False),
    sa.Column('status', AutoString(length=20), nullable=False),
    sa.Column('embedding_model_ref_id', AutoString(length=200), nullable=False),
    sa.Column('embedding_model_id_snapshot', AutoString(length=200), nullable=False),
    sa.Column('embedding_dimensions_snapshot', sa.Integer(), nullable=False),
    sa.Column('distance_metric', AutoString(length=20), nullable=False),
    sa.Column('chunker_type', AutoString(length=50), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('filterable_fields_json', AutoString(), nullable=False),
    sa.Column('vector_index_type', AutoString(length=50), nullable=False),
    sa.Column('vector_index_params_json', AutoString(), nullable=False),
    sa.Column('fts_index_params_json', AutoString(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('last_error', AutoString(), nullable=True),
    sa.Column('last_build_at', sa.DateTime(), nullable=True),
    sa.Column('last_ready_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['embedding_model_ref_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieval_indexes_embedding_model_ref_id'), 'retrieval_indexes', ['embedding_model_ref_id'], unique=False)
    op.create_index(op.f('ix_retrieval_indexes_index_key'), 'retrieval_indexes', ['index_key'], unique=True)
    op.create_index(op.f('ix_retrieval_indexes_status'), 'retrieval_indexes', ['status'], unique=False)
    op.create_index(op.f('ix_retrieval_indexes_table_name'), 'retrieval_indexes', ['table_name'], unique=False)
    op.create_table('revision_chapter_snapshots',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('revision_id', AutoString(), nullable=False),
    sa.Column('chapter_id', AutoString(), nullable=False),
    sa.Column('project_id', AutoString(), nullable=False),
    sa.Column('exists', sa.Boolean(), nullable=False),
    sa.Column('title', AutoString(length=200), nullable=True),
    sa.Column('content', AutoString(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('chapter_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id', 'chapter_id', name='uq_revision_chapter_snapshot')
    )
    op.create_index(op.f('ix_revision_chapter_snapshots_chapter_id'), 'revision_chapter_snapshots', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_revision_chapter_snapshots_created_at'), 'revision_chapter_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_revision_chapter_snapshots_project_id'), 'revision_chapter_snapshots', ['project_id'], unique=False)
    op.create_index(op.f('ix_revision_chapter_snapshots_revision_id'), 'revision_chapter_snapshots', ['revision_id'], unique=False)
    op.create_table('revision_note_category_snapshots',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('revision_id', AutoString(), nullable=False),
    sa.Column('category_id', AutoString(), nullable=False),
    sa.Column('project_id', AutoString(), nullable=False),
    sa.Column('exists', sa.Boolean(), nullable=False),
    sa.Column('parent_id', AutoString(), nullable=True),
    sa.Column('title', AutoString(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id', 'category_id', name='uq_revision_note_category_snapshot')
    )
    op.create_index(op.f('ix_revision_note_category_snapshots_category_id'), 'revision_note_category_snapshots', ['category_id'], unique=False)
    op.create_index(op.f('ix_revision_note_category_snapshots_created_at'), 'revision_note_category_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_revision_note_category_snapshots_parent_id'), 'revision_note_category_snapshots', ['parent_id'], unique=False)
    op.create_index(op.f('ix_revision_note_category_snapshots_project_id'), 'revision_note_category_snapshots', ['project_id'], unique=False)
    op.create_index(op.f('ix_revision_note_category_snapshots_revision_id'), 'revision_note_category_snapshots', ['revision_id'], unique=False)
    op.create_table('revision_note_snapshots',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('revision_id', AutoString(), nullable=False),
    sa.Column('note_id', AutoString(), nullable=False),
    sa.Column('project_id', AutoString(), nullable=False),
    sa.Column('exists', sa.Boolean(), nullable=False),
    sa.Column('category_id', AutoString(), nullable=True),
    sa.Column('title', AutoString(length=200), nullable=True),
    sa.Column('content', AutoString(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id', 'note_id', name='uq_revision_note_snapshot')
    )
    op.create_index(op.f('ix_revision_note_snapshots_category_id'), 'revision_note_snapshots', ['category_id'], unique=False)
    op.create_index(op.f('ix_revision_note_snapshots_created_at'), 'revision_note_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_revision_note_snapshots_note_id'), 'revision_note_snapshots', ['note_id'], unique=False)
    op.create_index(op.f('ix_revision_note_snapshots_project_id'), 'revision_note_snapshots', ['project_id'], unique=False)
    op.create_index(op.f('ix_revision_note_snapshots_revision_id'), 'revision_note_snapshots', ['revision_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('project_id', AutoString(), nullable=False),
    sa.Column('title', AutoString(length=200), nullable=False),
    sa.Column('mode', AutoString(length=20), nullable=False),
    sa.Column('token_input', sa.Integer(), nullable=False),
    sa.Column('token_output', sa.Integer(), nullable=False),
    sa.Column('token_cache', sa.Integer(), nullable=False),
    sa.Column('context_input_tokens', sa.Integer(), nullable=False),
    sa.Column('current_revision_id', AutoString(), nullable=True),
    sa.Column('current_message_id', AutoString(), nullable=True),
    sa.Column('agent_session_id', AutoString(), nullable=True),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('is_favorited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_revision_id'], ['revisions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_agent_session_id'), 'tasks', ['agent_session_id'], unique=False)
    op.create_index(op.f('ix_tasks_current_message_id'), 'tasks', ['current_message_id'], unique=False)
    op.create_index(op.f('ix_tasks_current_revision_id'), 'tasks', ['current_revision_id'], unique=False)
    op.create_index(op.f('ix_tasks_is_favorited'), 'tasks', ['is_favorited'], unique=False)
    op.create_index(op.f('ix_tasks_mode'), 'tasks', ['mode'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_table('world_info_entries',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('world_info_id', AutoString(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', AutoString(length=200), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('content', AutoString(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['world_info_id'], ['world_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_info_entries_order'), 'world_info_entries', ['order'], unique=False)
    op.create_index(op.f('ix_world_info_entries_uid'), 'world_info_entries', ['uid'], unique=False)
    op.create_index(op.f('ix_world_info_entries_world_info_id'), 'world_info_entries', ['world_info_id'], unique=False)
    op.create_table('agent_audit_logs',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('task_id', AutoString(), nullable=True),
    sa.Column('session_id', AutoString(), nullable=True),
    sa.Column('parent_session_id', AutoString(), nullable=True),
    sa.Column('child_run_id', AutoString(), nullable=True),
    sa.Column('project_id', AutoString(), nullable=False),
    sa.Column('chapter_id', AutoString(), nullable=True),
    sa.Column('revision_id', AutoString(), nullable=True),
    sa.Column('agent_node', AutoString(length=50), nullable=False),
    sa.Column('call_sequence', sa.Integer(), nullable=True),
    sa.Column('model_id', AutoString(), nullable=False),
    sa.Column('model_provider', AutoString(length=50), nullable=True),
    sa.Column('model_name', AutoString(length=100), nullable=True),
    sa.Column('request_messages', AutoString(), nullable=True),
    sa.Column('response_content', AutoString(), nullable=True),
    sa.Column('response_tool_calls', AutoString(), nullable=True),
    sa.Column('tool_call_results', AutoString(), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('tokens_total', sa.Integer(), nullable=False),
    sa.Column('token_cache', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('first_token_ms', sa.Integer(), nullable=True),
    sa.Column('status', AutoString(length=20), nullable=False),
    sa.Column('error_type', AutoString(length=50), nullable=True),
    sa.Column('error_message', AutoString(), nullable=True),
    sa.Column('error_status_code', sa.Integer(), nullable=True),
    sa.Column('tool_calls_count', sa.Integer(), nullable=False),
    sa.Column('tool_calls_success_count', sa.Integer(), nullable=False),
    sa.Column('tool_calls_failed_count', sa.Integer(), nullable=False),
    sa.Column('extra_data', AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_audit_logs_agent_node'), 'agent_audit_logs', ['agent_node'], unique=False)
    op.create_index(op.f('ix_agent_audit_logs_chapter_id'), 'agent_audit_logs', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_agent_audit_logs_child_run_id'), 'agent_audit_logs', ['child_run_id'], unique=False)
    op.create_index(op.f('ix_agent_audit_logs_created_at'), 'agent_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_audit_logs_model_id'), 'agent_audit_logs', ['model_id'], unique=False)
    op.create_index(op.f('ix_agent_audit_logs_model_provider'), 'agent_audit_logs', ['model_provider'], unique=False)
    op.create_index(op.f('ix_agent_audit_logs_parent_session_id'), 'agent_audit_logs', ['parent_session_id'], unique=False)
    op.create_index(op.f('ix_agent_audit_logs_project_id'), 'agent_audit_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_agent_audit_logs_revision_id'), 'agent_audit_logs', ['revision_id'], unique=False)
    op.create_index(op.f('ix_agent_audit_logs_session_id'), 'agent_audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_audit_logs_status'), 'agent_audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_audit_logs_task_id'), 'agent_audit_logs', ['task_id'], unique=False)
    op.create_table('agent_child_runs',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('parent_session_id', AutoString(length=64), nullable=False),
    sa.Column('parent_task_id', AutoString(length=64), nullable=False),
    sa.Column('parent_thread_id', AutoString(length=128), nullable=False),
    sa.Column('child_thread_id', AutoString(length=128), nullable=False),
    sa.Column('agent_key', AutoString(length=50), nullable=False),
    sa.Column('dispatch_id', AutoString(length=64), nullable=False),
    sa.Column('tool_call_id', AutoString(length=64), nullable=False),
    sa.Column('status', AutoString(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('request_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('pending_approval_id', AutoString(length=128), nullable=True),
    sa.Column('pending_approval_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('recycled_at', sa.DateTime(), nullable=True),
    sa.Column('last_assistant_content', sa.Text(), nullable=True),
    sa.Column('last_user_message_at', sa.DateTime(), nullable=True),
    sa.Column('last_completed_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_child_runs_agent_key'), 'agent_child_runs', ['agent_key'], unique=False)
    op.create_index(op.f('ix_agent_child_runs_child_thread_id'), 'agent_child_runs', ['child_thread_id'], unique=False)
    op.create_index(op.f('ix_agent_child_runs_completed_at'), 'agent_child_runs', ['completed_at'], unique=False)
    op.create_index(op.f('ix_agent_child_runs_created_at'), 'agent_child_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_child_runs_dispatch_id'), 'agent_child_runs', ['dispatch_id'], unique=False)
    op.create_index(op.f('ix_agent_child_runs_is_active'), 'agent_child_runs', ['is_active'], unique=False)
    op.create_index(op.f('ix_agent_child_runs_last_completed_at'), 'agent_child_runs', ['last_completed_at'], unique=False)
    op.create_index(op.f('ix_agent_child_runs_last_user_message_at'), 'agent_child_runs', ['last_user_message_at'], unique=False)
    op.create_index(op.f('ix_agent_child_runs_parent_session_id'), 'agent_child_runs', ['parent_session_id'], unique=False)
    op.create_index(op.f('ix_agent_child_runs_parent_task_id'), 'agent_child_runs', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_agent_child_runs_parent_thread_id'), 'agent_child_runs', ['parent_thread_id'], unique=False)
    op.create_index(op.f('ix_agent_child_runs_pending_approval_id'), 'agent_child_runs', ['pending_approval_id'], unique=False)
    op.create_index(op.f('ix_agent_child_runs_recycled_at'), 'agent_child_runs', ['recycled_at'], unique=False)
    op.create_index(op.f('ix_agent_child_runs_started_at'), 'agent_child_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_agent_child_runs_status'), 'agent_child_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_child_runs_tool_call_id'), 'agent_child_runs', ['tool_call_id'], unique=False)
    op.create_table('agent_context_compactions',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('session_id', AutoString(length=64), nullable=False),
    sa.Column('task_id', AutoString(length=64), nullable=False),
    sa.Column('project_id', AutoString(length=64), nullable=False),
    sa.Column('start_seq', sa.Integer(), nullable=False),
    sa.Column('end_seq', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('trigger', AutoString(length=20), nullable=False),
    sa.Column('source_input_tokens', sa.Integer(), nullable=False),
    sa.Column('summary_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_seq >= 0', name='ck_agent_context_compactions_end_seq_nonnegative'),
    sa.CheckConstraint('source_input_tokens >= 0', name='ck_agent_context_compactions_source_input_tokens_nonnegative'),
    sa.CheckConstraint('start_seq <= end_seq', name='ck_agent_context_compactions_valid_range'),
    sa.CheckConstraint('start_seq >= 0', name='ck_agent_context_compactions_start_seq_nonnegative'),
    sa.CheckConstraint('summary_tokens >= 0', name='ck_agent_context_compactions_summary_tokens_nonnegative'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_context_compactions_created_at'), 'agent_context_compactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_context_compactions_end_seq'), 'agent_context_compactions', ['end_seq'], unique=False)
    op.create_index(op.f('ix_agent_context_compactions_project_id'), 'agent_context_compactions', ['project_id'], unique=False)
    op.create_index(op.f('ix_agent_context_compactions_session_id'), 'agent_context_compactions', ['session_id'], unique=False)
    op.create_index('ix_agent_context_compactions_session_start_end', 'agent_context_compactions', ['session_id', 'start_seq', 'end_seq'], unique=False)
    op.create_index(op.f('ix_agent_context_compactions_start_seq'), 'agent_context_compactions', ['start_seq'], unique=False)
    op.create_index(op.f('ix_agent_context_compactions_task_id'), 'agent_context_compactions', ['task_id'], unique=False)
    op.create_index(op.f('ix_agent_context_compactions_trigger'), 'agent_context_compactions', ['trigger'], unique=False)
    op.create_table('agent_run_messages',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('session_id', AutoString(length=64), nullable=False),
    sa.Column('task_id', AutoString(length=64), nullable=False),
    sa.Column('project_id', AutoString(length=64), nullable=False),
    sa.Column('role', AutoString(length=20), nullable=False),
    sa.Column('agent_id', AutoString(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('reasoning_duration_ms', sa.Integer(), nullable=True),
    sa.Column('tool_calls', sa.Text(), nullable=True),
    sa.Column('tool_call_id', AutoString(length=64), nullable=True),
    sa.Column('tool_name', AutoString(length=64), nullable=True),
    sa.Column('status', AutoString(length=20), nullable=False),
    sa.Column('message_type', AutoString(length=50), nullable=False),
    sa.Column('display_channel', AutoString(length=20), nullable=False),
    sa.Column('llm_visibility', AutoString(length=20), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_messages_agent_id'), 'agent_run_messages', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_run_messages_created_at'), 'agent_run_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_run_messages_display_channel'), 'agent_run_messages', ['display_channel'], unique=False)
    op.create_index(op.f('ix_agent_run_messages_llm_visibility'), 'agent_run_messages', ['llm_visibility'], unique=False)
    op.create_index(op.f('ix_agent_run_messages_message_type'), 'agent_run_messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_agent_run_messages_project_id'), 'agent_run_messages', ['project_id'], unique=False)
    op.create_index(op.f('ix_agent_run_messages_role'), 'agent_run_messages', ['role'], unique=False)
    op.create_index(op.f('ix_agent_run_messages_seq'), 'agent_run_messages', ['seq'], unique=False)
    op.create_index(op.f('ix_agent_run_messages_session_id'), 'agent_run_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_run_messages_status'), 'agent_run_messages', ['status'], unique=False)
    op.create_index(op.f('ix_agent_run_messages_task_id'), 'agent_run_messages', ['task_id'], unique=False)
    op.create_index(op.f('ix_agent_run_messages_tool_call_id'), 'agent_run_messages', ['tool_call_id'], unique=False)
    op.create_table('chapter_summaries',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('project_id', AutoString(), nullable=False),
    sa.Column('summary_type', AutoString(length=20), nullable=False),
    sa.Column('status', AutoString(length=30), nullable=False),
    sa.Column('chapter_id', AutoString(), nullable=True),
    sa.Column('volume_id', AutoString(), nullable=True),
    sa.Column('chapter_order', sa.Integer(), nullable=True),
    sa.Column('start_order', sa.Integer(), nullable=True),
    sa.Column('end_order', sa.Integer(), nullable=True),
    sa.Column('start_time', AutoString(), nullable=False),
    sa.Column('end_time', AutoString(), nullable=False),
    sa.Column('characters_json', AutoString(), nullable=False),
    sa.Column('locations_json', AutoString(), nullable=False),
    sa.Column('summary', AutoString(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('error_message', AutoString(), nullable=True),
    sa.Column('source_content_normalized', AutoString(), nullable=False),
    sa.Column('source_chapter_ids_json', AutoString(), nullable=False),
    sa.Column('source_chapter_summary_signatures_json', AutoString(), nullable=False),
    sa.Column('model_id', AutoString(length=200), nullable=True),
    sa.Column('job_id', AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['volume_id'], ['volumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_summaries_chapter_id'), 'chapter_summaries', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_chapter_summaries_chapter_order'), 'chapter_summaries', ['chapter_order'], unique=False)
    op.create_index(op.f('ix_chapter_summaries_end_order'), 'chapter_summaries', ['end_order'], unique=False)
    op.create_index(op.f('ix_chapter_summaries_job_id'), 'chapter_summaries', ['job_id'], unique=False)
    op.create_index(op.f('ix_chapter_summaries_project_id'), 'chapter_summaries', ['project_id'], unique=False)
    op.create_index(op.f('ix_chapter_summaries_start_order'), 'chapter_summaries', ['start_order'], unique=False)
    op.create_index(op.f('ix_chapter_summaries_status'), 'chapter_summaries', ['status'], unique=False)
    op.create_index(op.f('ix_chapter_summaries_summary_type'), 'chapter_summaries', ['summary_type'], unique=False)
    op.create_index(op.f('ix_chapter_summaries_volume_id'), 'chapter_summaries', ['volume_id'], unique=False)
    op.create_table('commits',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('revision_id', AutoString(), nullable=False),
    sa.Column('chapter_id', AutoString(), nullable=False),
    sa.Column('operation', AutoString(length=20), nullable=False),
    sa.Column('snapshot_title', AutoString(length=200), nullable=True),
    sa.Column('snapshot_content', AutoString(), nullable=True),
    sa.Column('snapshot_word_count', sa.Integer(), nullable=True),
    sa.Column('snapshot_order', sa.Integer(), nullable=True),
    sa.Column('new_title', AutoString(length=200), nullable=True),
    sa.Column('new_content', AutoString(), nullable=True),
    sa.Column('new_word_count', sa.Integer(), nullable=True),
    sa.Column('new_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commits_chapter_id'), 'commits', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_commits_revision_id'), 'commits', ['revision_id'], unique=False)
    op.create_table('retrieval_chapter_index_states',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('project_id', AutoString(), nullable=False),
    sa.Column('chapter_id', AutoString(), nullable=False),
    sa.Column('index_key', AutoString(length=200), nullable=False),
    sa.Column('status', AutoString(length=30), nullable=False),
    sa.Column('source_hash', AutoString(length=128), nullable=True),
    sa.Column('embedding_model_ref_id', AutoString(length=200), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('job_id', AutoString(), nullable=True),
    sa.Column('item_id', AutoString(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['embedding_model_ref_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['background_job_items.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['background_jobs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'chapter_id', 'index_key', name='uq_retrieval_chapter_index_state')
    )
    op.create_index(op.f('ix_retrieval_chapter_index_states_chapter_id'), 'retrieval_chapter_index_states', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_retrieval_chapter_index_states_embedding_model_ref_id'), 'retrieval_chapter_index_states', ['embedding_model_ref_id'], unique=False)
    op.create_index(op.f('ix_retrieval_chapter_index_states_index_key'), 'retrieval_chapter_index_states', ['index_key'], unique=False)
    op.create_index(op.f('ix_retrieval_chapter_index_states_indexed_at'), 'retrieval_chapter_index_states', ['indexed_at'], unique=False)
    op.create_index(op.f('ix_retrieval_chapter_index_states_item_id'), 'retrieval_chapter_index_states', ['item_id'], unique=False)
    op.create_index(op.f('ix_retrieval_chapter_index_states_job_id'), 'retrieval_chapter_index_states', ['job_id'], unique=False)
    op.create_index(op.f('ix_retrieval_chapter_index_states_project_id'), 'retrieval_chapter_index_states', ['project_id'], unique=False)
    op.create_index(op.f('ix_retrieval_chapter_index_states_status'), 'retrieval_chapter_index_states', ['status'], unique=False)
    op.create_index(op.f('ix_retrieval_chapter_index_states_updated_at'), 'retrieval_chapter_index_states', ['updated_at'], unique=False)
    op.create_table('task_messages',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('task_id', AutoString(), nullable=False),
    sa.Column('role', AutoString(length=20), nullable=False),
    sa.Column('agent_id', AutoString(length=50), nullable=True),
    sa.Column('content', AutoString(), nullable=False),
    sa.Column('tool_calls', AutoString(), nullable=False),
    sa.Column('tool_call_id', AutoString(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.Column('message_type', AutoString(), nullable=True),
    sa.Column('message_status', AutoString(), nullable=True),
    sa.Column('display_channel', AutoString(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('correlation_id', AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_messages_agent_id'), 'task_messages', ['agent_id'], unique=False)
    op.create_index(op.f('ix_task_messages_correlation_id'), 'task_messages', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_task_messages_created_at'), 'task_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_messages_display_channel'), 'task_messages', ['display_channel'], unique=False)
    op.create_index(op.f('ix_task_messages_message_status'), 'task_messages', ['message_status'], unique=False)
    op.create_index(op.f('ix_task_messages_message_type'), 'task_messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_task_messages_role'), 'task_messages', ['role'], unique=False)
    op.create_index(op.f('ix_task_messages_task_id'), 'task_messages', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_messages_tool_call_id'), 'task_messages', ['tool_call_id'], unique=False)
    op.create_table('agent_child_run_requests',
    sa.Column('id', AutoString(), nullable=False),
    sa.Column('child_run_id', AutoString(length=64), nullable=False),
    sa.Column('parent_session_id', AutoString(length=64), nullable=False),
    sa.Column('parent_task_id', AutoString(length=64), nullable=False),
    sa.Column('request_kind', AutoString(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', AutoString(length=20), nullable=False),
    sa.Column('assistant_content', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_run_id'], ['agent_child_runs.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_child_run_requests_child_run_id'), 'agent_child_run_requests', ['child_run_id'], unique=False)
    op.create_index(op.f('ix_agent_child_run_requests_completed_at'), 'agent_child_run_requests', ['completed_at'], unique=False)
    op.create_index(op.f('ix_agent_child_run_requests_created_at'), 'agent_child_run_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_child_run_requests_parent_session_id'), 'agent_child_run_requests', ['parent_session_id'], unique=False)
    op.create_index(op.f('ix_agent_child_run_requests_parent_task_id'), 'agent_child_run_requests', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_agent_child_run_requests_request_kind'), 'agent_child_run_requests', ['request_kind'], unique=False)
    op.create_index(op.f('ix_agent_child_run_requests_seq'), 'agent_child_run_requests', ['seq'], unique=False)
    op.create_index(op.f('ix_agent_child_run_requests_started_at'), 'agent_child_run_requests', ['started_at'], unique=False)
    op.create_index(op.f('ix_agent_child_run_requests_status'), 'agent_child_run_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_child_run_requests_status'), table_name='agent_child_run_requests')
    op.drop_index(op.f('ix_agent_child_run_requests_started_at'), table_name='agent_child_run_requests')
    op.drop_index(op.f('ix_agent_child_run_requests_seq'), table_name='agent_child_run_requests')
    op.drop_index(op.f('ix_agent_child_run_requests_request_kind'), table_name='agent_child_run_requests')
    op.drop_index(op.f('ix_agent_child_run_requests_parent_task_id'), table_name='agent_child_run_requests')
    op.drop_index(op.f('ix_agent_child_run_requests_parent_session_id'), table_name='agent_child_run_requests')
    op.drop_index(op.f('ix_agent_child_run_requests_created_at'), table_name='agent_child_run_requests')
    op.drop_index(op.f('ix_agent_child_run_requests_completed_at'), table_name='agent_child_run_requests')
    op.drop_index(op.f('ix_agent_child_run_requests_child_run_id'), table_name='agent_child_run_requests')
    op.drop_table('agent_child_run_requests')
    op.drop_index(op.f('ix_task_messages_tool_call_id'), table_name='task_messages')
    op.drop_index(op.f('ix_task_messages_task_id'), table_name='task_messages')
    op.drop_index(op.f('ix_task_messages_role'), table_name='task_messages')
    op.drop_index(op.f('ix_task_messages_message_type'), table_name='task_messages')
    op.drop_index(op.f('ix_task_messages_message_status'), table_name='task_messages')
    op.drop_index(op.f('ix_task_messages_display_channel'), table_name='task_messages')
    op.drop_index(op.f('ix_task_messages_created_at'), table_name='task_messages')
    op.drop_index(op.f('ix_task_messages_correlation_id'), table_name='task_messages')
    op.drop_index(op.f('ix_task_messages_agent_id'), table_name='task_messages')
    op.drop_table('task_messages')
    op.drop_index(op.f('ix_retrieval_chapter_index_states_updated_at'), table_name='retrieval_chapter_index_states')
    op.drop_index(op.f('ix_retrieval_chapter_index_states_status'), table_name='retrieval_chapter_index_states')
    op.drop_index(op.f('ix_retrieval_chapter_index_states_project_id'), table_name='retrieval_chapter_index_states')
    op.drop_index(op.f('ix_retrieval_chapter_index_states_job_id'), table_name='retrieval_chapter_index_states')
    op.drop_index(op.f('ix_retrieval_chapter_index_states_item_id'), table_name='retrieval_chapter_index_states')
    op.drop_index(op.f('ix_retrieval_chapter_index_states_indexed_at'), table_name='retrieval_chapter_index_states')
    op.drop_index(op.f('ix_retrieval_chapter_index_states_index_key'), table_name='retrieval_chapter_index_states')
    op.drop_index(op.f('ix_retrieval_chapter_index_states_embedding_model_ref_id'), table_name='retrieval_chapter_index_states')
    op.drop_index(op.f('ix_retrieval_chapter_index_states_chapter_id'), table_name='retrieval_chapter_index_states')
    op.drop_table('retrieval_chapter_index_states')
    op.drop_index(op.f('ix_commits_revision_id'), table_name='commits')
    op.drop_index(op.f('ix_commits_chapter_id'), table_name='commits')
    op.drop_table('commits')
    op.drop_index(op.f('ix_chapter_summaries_volume_id'), table_name='chapter_summaries')
    op.drop_index(op.f('ix_chapter_summaries_summary_type'), table_name='chapter_summaries')
    op.drop_index(op.f('ix_chapter_summaries_status'), table_name='chapter_summaries')
    op.drop_index(op.f('ix_chapter_summaries_start_order'), table_name='chapter_summaries')
    op.drop_index(op.f('ix_chapter_summaries_project_id'), table_name='chapter_summaries')
    op.drop_index(op.f('ix_chapter_summaries_job_id'), table_name='chapter_summaries')
    op.drop_index(op.f('ix_chapter_summaries_end_order'), table_name='chapter_summaries')
    op.drop_index(op.f('ix_chapter_summaries_chapter_order'), table_name='chapter_summaries')
    op.drop_index(op.f('ix_chapter_summaries_chapter_id'), table_name='chapter_summaries')
    op.drop_table('chapter_summaries')
    op.drop_index(op.f('ix_agent_run_messages_tool_call_id'), table_name='agent_run_messages')
    op.drop_index(op.f('ix_agent_run_messages_task_id'), table_name='agent_run_messages')
    op.drop_index(op.f('ix_agent_run_messages_status'), table_name='agent_run_messages')
    op.drop_index(op.f('ix_agent_run_messages_session_id'), table_name='agent_run_messages')
    op.drop_index(op.f('ix_agent_run_messages_seq'), table_name='agent_run_messages')
    op.drop_index(op.f('ix_agent_run_messages_role'), table_name='agent_run_messages')
    op.drop_index(op.f('ix_agent_run_messages_project_id'), table_name='agent_run_messages')
    op.drop_index(op.f('ix_agent_run_messages_message_type'), table_name='agent_run_messages')
    op.drop_index(op.f('ix_agent_run_messages_llm_visibility'), table_name='agent_run_messages')
    op.drop_index(op.f('ix_agent_run_messages_display_channel'), table_name='agent_run_messages')
    op.drop_index(op.f('ix_agent_run_messages_created_at'), table_name='agent_run_messages')
    op.drop_index(op.f('ix_agent_run_messages_agent_id'), table_name='agent_run_messages')
    op.drop_table('agent_run_messages')
    op.drop_index(op.f('ix_agent_context_compactions_trigger'), table_name='agent_context_compactions')
    op.drop_index(op.f('ix_agent_context_compactions_task_id'), table_name='agent_context_compactions')
    op.drop_index(op.f('ix_agent_context_compactions_start_seq'), table_name='agent_context_compactions')
    op.drop_index('ix_agent_context_compactions_session_start_end', table_name='agent_context_compactions')
    op.drop_index(op.f('ix_agent_context_compactions_session_id'), table_name='agent_context_compactions')
    op.drop_index(op.f('ix_agent_context_compactions_project_id'), table_name='agent_context_compactions')
    op.drop_index(op.f('ix_agent_context_compactions_end_seq'), table_name='agent_context_compactions')
    op.drop_index(op.f('ix_agent_context_compactions_created_at'), table_name='agent_context_compactions')
    op.drop_table('agent_context_compactions')
    op.drop_index(op.f('ix_agent_child_runs_tool_call_id'), table_name='agent_child_runs')
    op.drop_index(op.f('ix_agent_child_runs_status'), table_name='agent_child_runs')
    op.drop_index(op.f('ix_agent_child_runs_started_at'), table_name='agent_child_runs')
    op.drop_index(op.f('ix_agent_child_runs_recycled_at'), table_name='agent_child_runs')
    op.drop_index(op.f('ix_agent_child_runs_pending_approval_id'), table_name='agent_child_runs')
    op.drop_index(op.f('ix_agent_child_runs_parent_thread_id'), table_name='agent_child_runs')
    op.drop_index(op.f('ix_agent_child_runs_parent_task_id'), table_name='agent_child_runs')
    op.drop_index(op.f('ix_agent_child_runs_parent_session_id'), table_name='agent_child_runs')
    op.drop_index(op.f('ix_agent_child_runs_last_user_message_at'), table_name='agent_child_runs')
    op.drop_index(op.f('ix_agent_child_runs_last_completed_at'), table_name='agent_child_runs')
    op.drop_index(op.f('ix_agent_child_runs_is_active'), table_name='agent_child_runs')
    op.drop_index(op.f('ix_agent_child_runs_dispatch_id'), table_name='agent_child_runs')
    op.drop_index(op.f('ix_agent_child_runs_created_at'), table_name='agent_child_runs')
    op.drop_index(op.f('ix_agent_child_runs_completed_at'), table_name='agent_child_runs')
    op.drop_index(op.f('ix_agent_child_runs_child_thread_id'), table_name='agent_child_runs')
    op.drop_index(op.f('ix_agent_child_runs_agent_key'), table_name='agent_child_runs')
    op.drop_table('agent_child_runs')
    op.drop_index(op.f('ix_agent_audit_logs_task_id'), table_name='agent_audit_logs')
    op.drop_index(op.f('ix_agent_audit_logs_status'), table_name='agent_audit_logs')
    op.drop_index(op.f('ix_agent_audit_logs_session_id'), table_name='agent_audit_logs')
    op.drop_index(op.f('ix_agent_audit_logs_revision_id'), table_name='agent_audit_logs')
    op.drop_index(op.f('ix_agent_audit_logs_project_id'), table_name='agent_audit_logs')
    op.drop_index(op.f('ix_agent_audit_logs_parent_session_id'), table_name='agent_audit_logs')
    op.drop_index(op.f('ix_agent_audit_logs_model_provider'), table_name='agent_audit_logs')
    op.drop_index(op.f('ix_agent_audit_logs_model_id'), table_name='agent_audit_logs')
    op.drop_index(op.f('ix_agent_audit_logs_created_at'), table_name='agent_audit_logs')
    op.drop_index(op.f('ix_agent_audit_logs_child_run_id'), table_name='agent_audit_logs')
    op.drop_index(op.f('ix_agent_audit_logs_chapter_id'), table_name='agent_audit_logs')
    op.drop_index(op.f('ix_agent_audit_logs_agent_node'), table_name='agent_audit_logs')
    op.drop_table('agent_audit_logs')
    op.drop_index(op.f('ix_world_info_entries_world_info_id'), table_name='world_info_entries')
    op.drop_index(op.f('ix_world_info_entries_uid'), table_name='world_info_entries')
    op.drop_index(op.f('ix_world_info_entries_order'), table_name='world_info_entries')
    op.drop_table('world_info_entries')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_mode'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_favorited'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_current_revision_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_current_message_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_agent_session_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_revision_note_snapshots_revision_id'), table_name='revision_note_snapshots')
    op.drop_index(op.f('ix_revision_note_snapshots_project_id'), table_name='revision_note_snapshots')
    op.drop_index(op.f('ix_revision_note_snapshots_note_id'), table_name='revision_note_snapshots')
    op.drop_index(op.f('ix_revision_note_snapshots_created_at'), table_name='revision_note_snapshots')
    op.drop_index(op.f('ix_revision_note_snapshots_category_id'), table_name='revision_note_snapshots')
    op.drop_table('revision_note_snapshots')
    op.drop_index(op.f('ix_revision_note_category_snapshots_revision_id'), table_name='revision_note_category_snapshots')
    op.drop_index(op.f('ix_revision_note_category_snapshots_project_id'), table_name='revision_note_category_snapshots')
    op.drop_index(op.f('ix_revision_note_category_snapshots_parent_id'), table_name='revision_note_category_snapshots')
    op.drop_index(op.f('ix_revision_note_category_snapshots_created_at'), table_name='revision_note_category_snapshots')
    op.drop_index(op.f('ix_revision_note_category_snapshots_category_id'), table_name='revision_note_category_snapshots')
    op.drop_table('revision_note_category_snapshots')
    op.drop_index(op.f('ix_revision_chapter_snapshots_revision_id'), table_name='revision_chapter_snapshots')
    op.drop_index(op.f('ix_revision_chapter_snapshots_project_id'), table_name='revision_chapter_snapshots')
    op.drop_index(op.f('ix_revision_chapter_snapshots_created_at'), table_name='revision_chapter_snapshots')
    op.drop_index(op.f('ix_revision_chapter_snapshots_chapter_id'), table_name='revision_chapter_snapshots')
    op.drop_table('revision_chapter_snapshots')
    op.drop_index(op.f('ix_retrieval_indexes_table_name'), table_name='retrieval_indexes')
    op.drop_index(op.f('ix_retrieval_indexes_status'), table_name='retrieval_indexes')
    op.drop_index(op.f('ix_retrieval_indexes_index_key'), table_name='retrieval_indexes')
    op.drop_index(op.f('ix_retrieval_indexes_embedding_model_ref_id'), table_name='retrieval_indexes')
    op.drop_table('retrieval_indexes')
    op.drop_index(op.f('ix_notes_project_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_category_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_chapters_volume_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_project_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_order'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_background_job_events_sequence'), table_name='background_job_events')
    op.drop_index(op.f('ix_background_job_events_job_id'), table_name='background_job_events')
    op.drop_index(op.f('ix_background_job_events_item_id'), table_name='background_job_events')
    op.drop_index(op.f('ix_background_job_events_event_type'), table_name='background_job_events')
    op.drop_index(op.f('ix_background_job_events_created_at'), table_name='background_job_events')
    op.drop_table('background_job_events')
    op.drop_index(op.f('ix_world_info_project_id'), table_name='world_info')
    op.drop_table('world_info')
    op.drop_index(op.f('ix_volumes_project_id'), table_name='volumes')
    op.drop_index(op.f('ix_volumes_order'), table_name='volumes')
    op.drop_table('volumes')
    op.drop_index(op.f('ix_revisions_user_message_seq'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_user_message_id'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_task_id'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_status'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_started_at'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_revision_type'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_project_id'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_pre_run_checkpoint_id'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_parent_revision_id'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_is_checkpoint'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_graph_thread_id'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_finished_at'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_created_at'), table_name='revisions')
    op.drop_table('revisions')
    op.drop_index(op.f('ix_prompt_entries_uid'), table_name='prompt_entries')
    op.drop_table('prompt_entries')
    op.drop_index(op.f('ix_plan_todos_status'), table_name='plan_todos')
    op.drop_index(op.f('ix_plan_todos_sort_index'), table_name='plan_todos')
    op.drop_index(op.f('ix_plan_todos_plan_id'), table_name='plan_todos')
    op.drop_index(op.f('ix_plan_todos_created_at'), table_name='plan_todos')
    op.drop_table('plan_todos')
    op.drop_index(op.f('ix_note_categories_project_id'), table_name='note_categories')
    op.drop_index(op.f('ix_note_categories_parent_id'), table_name='note_categories')
    op.drop_table('note_categories')
    op.drop_index(op.f('ix_models_task_type'), table_name='models')
    op.drop_index(op.f('ix_models_provider_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_background_job_items_updated_at'), table_name='background_job_items')
    op.drop_index(op.f('ix_background_job_items_type'), table_name='background_job_items')
    op.drop_index(op.f('ix_background_job_items_status'), table_name='background_job_items')
    op.drop_index(op.f('ix_background_job_items_order_index'), table_name='background_job_items')
    op.drop_index(op.f('ix_background_job_items_job_id'), table_name='background_job_items')
    op.drop_index(op.f('ix_background_job_items_item_key'), table_name='background_job_items')
    op.drop_table('background_job_items')
    op.drop_index(op.f('ix_writing_activity_events_task_id'), table_name='writing_activity_events')
    op.drop_index(op.f('ix_writing_activity_events_source'), table_name='writing_activity_events')
    op.drop_index(op.f('ix_writing_activity_events_revision_id'), table_name='writing_activity_events')
    op.drop_index(op.f('ix_writing_activity_events_project_id'), table_name='writing_activity_events')
    op.drop_index(op.f('ix_writing_activity_events_operation'), table_name='writing_activity_events')
    op.drop_index(op.f('ix_writing_activity_events_created_at'), table_name='writing_activity_events')
    op.drop_index(op.f('ix_writing_activity_events_chapter_id'), table_name='writing_activity_events')
    op.drop_index(op.f('ix_writing_activity_events_agent_session_id'), table_name='writing_activity_events')
    op.drop_table('writing_activity_events')
    op.drop_index(op.f('ix_skills_skill_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_is_enabled'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_table('prompt_chain_versions')
    op.drop_table('projects')
    op.drop_index(op.f('ix_plans_status'), table_name='plans')
    op.drop_index(op.f('ix_plans_scope_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_created_at'), table_name='plans')
    op.drop_table('plans')
    op.drop_table('model_providers')
    op.drop_index(op.f('ix_background_jobs_updated_at'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_type'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_subject_type'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_subject_id'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_status'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_queue'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_next_run_at'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_locked_by'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_locked_at'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_lease_expires_at'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_heartbeat_at'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_cancel_requested_at'), table_name='background_jobs')
    op.drop_table('background_jobs')
    op.drop_table('agent_rules')
    op.drop_table('agent_memories')
    op.drop_index(op.f('ix_agent_definitions_source'), table_name='agent_definitions')
    op.drop_index(op.f('ix_agent_definitions_order_index'), table_name='agent_definitions')
    op.drop_index(op.f('ix_agent_definitions_kind'), table_name='agent_definitions')
    op.drop_index(op.f('ix_agent_definitions_key'), table_name='agent_definitions')
    op.drop_index(op.f('ix_agent_definitions_enabled'), table_name='agent_definitions')
    op.drop_table('agent_definitions')
    # ### end Alembic commands ###
