name: Umpan Balik Bug
description: Laporkan Bug yang ditemui selama penggunaan
labels:
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: Deskripsi Masalah
      placeholder: |
        Dalam kondisi apa masalah apa yang muncul?
        Perilaku yang diharapkan: ...
        Perilaku sebenarnya: ...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Langkah Reproduksi
      placeholder: |
        Langkah reproduksi:
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log, Tangkapan Layar, atau Rekaman Layar
      description: |
        Silakan unggah atau tempelkan log error, tangkapan layar, atau rekaman layar yang sudah disamarkan;
        untuk menjaga keamanan privasi Anda, mohon jangan menyertakan kunci, token, atau informasi pribadi lainnya.
      render: shell
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Versi OpenFic
      placeholder: "misalnya: v0.7.5"
    validations:
      required: true

  - type: dropdown
    id: system
    attributes:
      label: Sistem Operasi
      options:
        - Windows
        - macOS
        - Linux
        - Lainnya
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform Eksekusi
      options:
        - Aplikasi desktop
        - Paket Python
        - Image Docker
        - Lainnya
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: Pemeriksaan Sebelum Mengirim
      options:
        - label: Saya sudah mencari Issue yang ada dan tidak menemukan masalah duplikat
          required: true
        - label: Saya memastikan tidak menyertakan kunci, token, atau informasi sensitif lainnya dalam konten
          required: true
