blank_issues_enabled: false
contact_links:
  - name: 📕 Dokumentasi Proyek
    url: https://github.com/syrizelink/OpenFic#readme
    about: Mohon periksa terlebih dahulu penjelasan proyek dan Issue yang sudah ada.
