name: Saran Fitur
description: Ajukan saran perbaikan atau fitur baru
labels:
  - enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Saran Perbaikan / Deskripsi Fitur Baru
      description: |
        Jelaskan secara detail fitur baru yang Anda harapkan untuk masalah yang Anda ajukan, termasuk skenario penggunaannya
        Jika memungkinkan, sertakan juga jawaban atas "mengapa dibutuhkan" dan "dalam skenario apa dibutuhkan"
        Jika Anda belum memperbarui ke versi terbaru, mohon perbarui terlebih dahulu, kadang saran Anda sudah diimplementasikan
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Versi OpenFic
      placeholder: "misalnya: v0.7.5"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Informasi Tambahan
      description: Anda dapat menyertakan prototipe, tangkapan layar, tautan referensi, atau konteks lainnya.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pemeriksaan Sebelum Mengirim
      options:
        - label: Saya sudah mencari Issue yang ada dan tidak menemukan saran duplikat
          required: true
