name: Masalah Lainnya
description: Bertanya atau mengajukan masalah terkait lainnya
labels:
  - question
body:
  - type: textarea
    id: question
    attributes:
      label: Deskripsi Masalah
      description: Mohon jelaskan masalah Anda dengan jelas dan akurat
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Versi OpenFic
      placeholder: "misalnya: v0.7.5"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Informasi Tambahan
      description: |
        Silakan unggah atau tempelkan log error, tangkapan layar, atau rekaman layar yang sudah disamarkan;
        untuk menjaga keamanan privasi Anda, mohon jangan menyertakan kunci, token, atau informasi pribadi lainnya.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pemeriksaan Sebelum Mengirim
      options:
        - label: Saya sudah mencari Issue yang ada dan tidak menemukan masalah duplikat
          required: true
