"""Add cover_path to projects

Revision ID: 001
Revises:
Create Date: 2025-12-24 17:58:21.504849

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("cover_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),  # type: ignore[attr-defined]
    )  # type: ignore[call-arg]
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "cover_path")
    # ### end Alembic commands ###
