"""Lightweight retrieval settings with no native vector dependencies."""

SETTING_KEY_INDEX_MODE = "index_mode"
SETTING_KEY_INDEX_ENABLED_PROJECTS = "index_enabled_projects"
SETTING_KEY_INDEX_CHUNK_SIZE = "index_chunk_size"
SETTING_KEY_INDEX_CHUNK_OVERLAP = "index_chunk_overlap"
SETTING_KEY_INDEX_AUTO_STRATEGY = "index_auto_strategy"
SETTING_KEY_INDEX_RERANK_ENABLED = "index_rerank_enabled"
SETTING_KEY_DEFAULT_RERANK_MODEL = "default_rerank_model"

INDEX_MODE_OFF = "off"
INDEX_MODE_ALL = "all"
INDEX_MODE_SELECTED = "selected"
INDEX_AUTO_STRATEGY_IMMEDIATE = "immediate"
INDEX_AUTO_STRATEGY_AGENT_DECIDED = "agent_decided"
INDEX_AUTO_STRATEGY_OFF = "off"

DEFAULT_INDEX_MODE = INDEX_MODE_OFF
DEFAULT_INDEX_AUTO_STRATEGY = INDEX_AUTO_STRATEGY_OFF
DEFAULT_INDEX_CHUNK_SIZE = 800
DEFAULT_INDEX_CHUNK_OVERLAP = 100
DEFAULT_INDEX_RERANK_ENABLED = False
DEFAULT_INDEX_RERANK_MODEL = ""

VALID_INDEX_MODES = {INDEX_MODE_OFF, INDEX_MODE_ALL, INDEX_MODE_SELECTED}
VALID_INDEX_AUTO_STRATEGIES = {
    INDEX_AUTO_STRATEGY_IMMEDIATE,
    INDEX_AUTO_STRATEGY_AGENT_DECIDED,
    INDEX_AUTO_STRATEGY_OFF,
}
